2020-10-06 09:25:45,301 INFO    MainThread:3984 [wandb_init.py:_log_setup():307] Logging user logs to wandb\run-20201006_092545-1lppbqpm\logs\debug.log
2020-10-06 09:25:45,302 INFO    MainThread:3984 [wandb_init.py:_log_setup():308] Logging internal logs to wandb\run-20201006_092545-1lppbqpm\logs\debug-internal.log
2020-10-06 09:25:45,302 INFO    MainThread:3984 [wandb_setup.py:_flush():68] setting env: {}
2020-10-06 09:25:45,302 INFO    MainThread:3984 [wandb_setup.py:_flush():68] setting user settings: {}
2020-10-06 09:25:45,302 INFO    MainThread:3984 [wandb_setup.py:_flush():68] multiprocessing start_methods=spawn
2020-10-06 09:25:45,302 WARNING MainThread:3984 [wandb_setup.py:_flush():68] Ignoring settings passed to wandb.setup() which has already been configured.
2020-10-06 09:25:45,309 INFO    MainThread:3984 [wandb_settings.py:_console():393] Set PYTHONLEGACYWINDOWSSTDIO environment variable to enable proper console logging on Windows. Falling back to wrapping stdout/err.
2020-10-06 09:25:45,454 WARNING MainThread:3984 [wandb_setup.py:__init__():209] Ignoring settings passed to wandb.setup() which has already been configured.
2020-10-06 09:25:47,536 WARNING MainThread:3984 [wandb_init.py:init():494] interrupted
Traceback (most recent call last):
  File "C:\Users\marcello.borges\AppData\Local\Programs\Python\Python36\lib\site-packages\wandb\sdk\wandb_init.py", line 477, in init
    run = wi.init()
  File "C:\Users\marcello.borges\AppData\Local\Programs\Python\Python36\lib\site-packages\wandb\sdk\wandb_init.py", line 356, in init
    _backend=backend, _disable_warning=True, _settings=self.settings
  File "C:\Users\marcello.borges\AppData\Local\Programs\Python\Python36\lib\site-packages\wandb\sdk\wandb_login.py", line 102, in _login
    res = _backend.interface.communicate_login(key, anonymous)
  File "C:\Users\marcello.borges\AppData\Local\Programs\Python\Python36\lib\site-packages\wandb\interface\interface.py", line 442, in communicate_login
    result = self._communicate(rec, timeout=timeout)
  File "C:\Users\marcello.borges\AppData\Local\Programs\Python\Python36\lib\site-packages\wandb\interface\interface.py", line 437, in _communicate
    return future.get(timeout)
  File "C:\Users\marcello.borges\AppData\Local\Programs\Python\Python36\lib\site-packages\wandb\interface\interface.py", line 58, in get
    is_set = self._object_ready.wait(timeout)
  File "C:\Users\marcello.borges\AppData\Local\Programs\Python\Python36\lib\threading.py", line 551, in wait
    signaled = self._cond.wait(timeout)
  File "C:\Users\marcello.borges\AppData\Local\Programs\Python\Python36\lib\threading.py", line 299, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
2020-10-06 09:25:47,574 INFO    MainThread:3984 [internal.py:handle_exit():137] Internal process exited
