2020-10-08 09:47:09,962 INFO    MainThread:31848 [wandb_init.py:_log_setup():307] Logging user logs to wandb\run-20201008_094709-8ardbbaf\logs\debug.log
2020-10-08 09:47:09,962 INFO    MainThread:31848 [wandb_init.py:_log_setup():308] Logging internal logs to wandb\run-20201008_094709-8ardbbaf\logs\debug-internal.log
2020-10-08 09:47:09,962 INFO    MainThread:31848 [wandb_setup.py:_flush():68] setting env: {}
2020-10-08 09:47:09,962 INFO    MainThread:31848 [wandb_setup.py:_flush():68] setting user settings: {}
2020-10-08 09:47:09,963 INFO    MainThread:31848 [wandb_setup.py:_flush():68] multiprocessing start_methods=spawn
2020-10-08 09:47:09,963 WARNING MainThread:31848 [wandb_setup.py:_flush():68] Ignoring settings passed to wandb.setup() which has already been configured.
2020-10-08 09:47:09,965 INFO    MainThread:31848 [wandb_settings.py:_console():393] Set PYTHONLEGACYWINDOWSSTDIO environment variable to enable proper console logging on Windows. Falling back to wrapping stdout/err.
2020-10-08 09:47:10,106 WARNING MainThread:31848 [wandb_setup.py:__init__():209] Ignoring settings passed to wandb.setup() which has already been configured.
2020-10-08 09:47:13,342 INFO    MainThread:31848 [wandb_run.py:_console_start():1134] atexit reg
2020-10-08 09:47:13,343 INFO    MainThread:31848 [wandb_settings.py:_console():393] Set PYTHONLEGACYWINDOWSSTDIO environment variable to enable proper console logging on Windows. Falling back to wrapping stdout/err.
2020-10-08 09:47:13,343 INFO    MainThread:31848 [wandb_run.py:_redirect():1009] redirect: SettingsConsole.REDIRECT
2020-10-08 09:47:13,344 INFO    MainThread:31848 [wandb_run.py:_redirect():1012] Redirecting console.
2020-10-08 09:47:13,344 ERROR   MainThread:31848 [redirect.py:install():184] Set PYTHONLEGACYWINDOWSSTDIO environment variable to enable console logging on Windows.
2020-10-08 09:47:13,344 ERROR   MainThread:31848 [wandb_run.py:_redirect():1059] Failed to redirect.
Traceback (most recent call last):
  File "C:\Users\marcello.borges\AppData\Local\Programs\Python\Python36\lib\site-packages\wandb\sdk\wandb_run.py", line 1052, in _redirect
    out_redir.install()
  File "C:\Users\marcello.borges\AppData\Local\Programs\Python\Python36\lib\site-packages\wandb\lib\redirect.py", line 185, in install
    raise Exception(msg)
Exception: Set PYTHONLEGACYWINDOWSSTDIO environment variable to enable console logging on Windows.
2020-10-08 09:47:13,345 INFO    MainThread:31848 [wandb_watch.py:watch():32] Watching
2020-10-08 09:47:13,345 INFO    MainThread:31848 [wandb_watch.py:watch():32] Watching
2020-10-08 09:50:15,758 INFO    MainThread:31848 [wandb_run.py:_atexit_cleanup():1112] got exitcode: 255
2020-10-08 09:50:15,759 INFO    MainThread:31848 [wandb_run.py:_restore():1084] restore
2020-10-08 09:50:15,762 INFO    MainThread:31848 [wandb_run.py:_wait_for_finish():1216] got exit ret: uuid: "197c1bce8a7d4200a7e42731cf2ebe14"
response {
  poll_exit_response {
    file_counts {
      wandb_count: 1
      media_count: 2
    }
    pusher_stats {
      uploaded_bytes: 1824
      total_bytes: 1824
    }
  }
}

2020-10-08 09:50:17,764 INFO    MainThread:31848 [wandb_run.py:_wait_for_finish():1216] got exit ret: uuid: "c0b82ee3eb4d4ed9a18da291a9ad5e25"
response {
  poll_exit_response {
    file_counts {
      wandb_count: 4
      media_count: 2
    }
    pusher_stats {
      uploaded_bytes: 4975
      total_bytes: 4975
    }
  }
}

2020-10-08 09:50:19,767 INFO    MainThread:31848 [wandb_run.py:_wait_for_finish():1216] got exit ret: uuid: "c94e375887c24f4a8c8b563b8ee2a24b"
response {
  poll_exit_response {
    done: true
    exit_result {
    }
    file_counts {
      wandb_count: 4
      media_count: 2
    }
    pusher_stats {
      uploaded_bytes: 4975
      total_bytes: 4975
    }
  }
}

2020-10-08 09:50:20,837 INFO    MainThread:31848 [wandb_run.py:_show_summary():1323] rendering summary
2020-10-08 09:50:20,839 INFO    MainThread:31848 [wandb_run.py:_show_history():1347] rendering history
2020-10-08 09:50:20,841 INFO    MainThread:31848 [wandb_run.py:_show_files():1363] logging synced files
2020-10-08 09:50:20,843 INFO    MainThread:31848 [internal.py:handle_exit():137] Internal process exited
